### ISSUE TITLE
Not work (or i just dont know how to do it)

### ISSUE THREAD

**Issue by Liveguide125** [JokerJosh1234/EchoBot#1]
When i open the sln it says that i need to install or update to the .net version 4.8. So i go to the dot net site and download version 4.8.1 then when i run the application to update my dot net. It says that I already have version 4.8.

**Comment by JokerJosh1234** [comment]
Hello, you can download all of the project files and create your own console application and import all of the files into the new project

**Comment by Liveguide125** [comment]
Ok, thanks.
